### ISSUE TITLE
the demo and ipcam stream can`t work

### ISSUE THREAD

**Issue by 493326889** [imonology/Kurento-H264#1]
the demo and ipcam stream can`t work

**Comment by bluet** [comment]
Hello @493326889 thanks for reporting,
Could you describe the problem/procedure and paste the error msg you got?
Thanks

**Comment by 493326889** [comment]
can this demo support http h264 stream ?

**Comment by 493326889** [comment]
Connection received with sessionId cso_Cz6tDZ7ntsXZM3FK0gOgqrL4S3dF
Connection cso_Cz6tDZ7ntsXZM3FK0gOgqrL4S3dF received message  { id: 'start',
  sdpOffer: 'v=0\r\no=- 3121596056445259028 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:U/er\r\na=ice-pwd:dtfCsUnBiL9aGkqEd41jg6mR\r\na=fingerprint:sha-256 4E:A7:6E:30:C8:74:60:2F:9C:8E:33:FD:07:16:28:79:D4:93:F8:4E:1E:9A:AF:E9:93:92:F4:60:85:F5:5B:C0\r\na=setup:actpass\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 isac/16000\r\na=rtpmap:104 isac/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 cn/32000\r\na=rtpmap:105 cn/16000\r\na=rtpmap:13 cn/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 98 100 102 127 97 99 101 125\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:U/er\r\na=ice-pwd:dtfCsUnBiL9aGkqEd41jg6mR\r\na=fingerprint:sha-256 4E:A7:6E:30:C8:74:60:2F:9C:8E:33:FD:07:16:28:79:D4:93:F8:4E:1E:9A:AF:E9:93:92:F4:60:85:F5:5B:C0\r\na=setup:actpass\r\na=mid:video\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtpmap:100 H264/90000\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:102 red/90000\r\na=rtpmap:127 ulpfec/90000\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:125 rtx/90000\r\na=fmtp:125 apt=102\r\n' }
Connection cso_Cz6tDZ7ntsXZM3FK0gOgqrL4S3dF received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:2919114929 1 udp 2122260223 10.68.105.126 55431 typ host generation 0 ufrag U/er network-id 1 network-cost 10',
     sdpMid: 'audio',
     sdpMLineIndex: 0 } }
Queueing candidate
Connection cso_Cz6tDZ7ntsXZM3FK0gOgqrL4S3dF received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:2919114929 1 udp 2122260223 10.68.105.126 64546 typ host generation 0 ufrag U/er network-id 1 network-cost 10',
     sdpMid: 'video',
     sdpMLineIndex: 1 } }
Queueing candidate
Connection cso_Cz6tDZ7ntsXZM3FK0gOgqrL4S3dF received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:3816674369 1 tcp 1518280447 10.68.105.126 9 typ host tcptype active generation 0 ufrag U/er network-id 1 network-cost 10',
     sdpMid: 'audio',
     sdpMLineIndex: 0 } }
Queueing candidate
Connection cso_Cz6tDZ7ntsXZM3FK0gOgqrL4S3dF received message  { id: 'onIceCandidate',
  candidate:
   { candidate: 'candidate:3816674369 1 tcp 1518280447 10.68.105.126 9 typ host tcptype active generation 0 ufrag U/er network-id 1 network-cost 10',
     sdpMid: 'video',
     sdpMLineIndex: 1 } }
Queueing candidate

server.js log   the program stop here

**Comment by 493326889** [comment]
ok  can work .it is the stun probleam.
when the kurento fetch the h264 strem , it change to vp8/opmus to chrome?

**Comment by bluet** [comment]
@493326889 as described in https://github.com/imonology/Kurento-H264/blob/master/README.md it uses H264 / WebRTC.

We've developed and migrated to another solution based on Broadway, which you can find here https://github.com/imonology/scalra-video

**Comment by bluet** [comment]
no updates for a long time, so closing this issue

**Comment by sraza295** [comment]
Getting same error
